/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SimpleImage = {
  asset?: SanityImageAssetReference;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SimplePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

// Identidad global de la marca — usada en todo el sitio.
// El contenido profundo de /marca va en Page con template 'about'.
export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  heroPhoto?: SimpleImage;
  mission?: SimplePortableText;
  vision?: SimplePortableText;
  logo?: SimpleImage;
  socialLinks?: Array<{ platform?: string; url?: string }>;
};

export type PageTemplate = "home" | "blog" | "products" | "about" | "default";

// Campos exclusivos de template: 'about'.
// Los datos globales (nombre, foto, misión) vienen del documento brand-{lang}.
export type AboutContent = {
  intro?: string;
  historiaPhoto?: SimpleImage;
  historia?: SimplePortableText;
  filosofia?: Array<{ title?: string; desc?: string }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  template?: PageTemplate;
  // Campos genéricos (home · blog · products · default)
  hero?: {
    heading?: string;
    subheading?: string;
    image?: CoverImage;
    cta?: {
      label?: string;
      href?: string;
    };
  };
  body?: BlockContent;
  // Campos exclusivos de template 'about'
  aboutContent?: AboutContent;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  role?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navLinks?: Array<{
    label?: {
      es?: string;
      en?: string;
    };
    href?: string;
    _key: string;
  }>;
  socialLinks?: {
    instagram?: string;
    youtube?: string;
    facebook?: string;
  };
  affiliateDisclosure?: {
    es?: string;
    en?: string;
  };
  defaultSeo?: {
    title?: {
      es?: string;
      en?: string;
    };
    description?: {
      es?: string;
      en?: string;
    };
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type ProductList = {
  _type: "productList";
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
};

export type YoutubeEmbed = {
  _type: "youtubeEmbed";
  url?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: CoverImage;
};

export type CoverImage = {
  _type: "coverImage";
  asset?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  externalUrl?: string;
  alt?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & YoutubeEmbed)
  | ({
      _key: string;
    } & ProductList)
>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: PostReference | ProductReference;
  language?: string;
};

export type ProductCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productCategory";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  name?: string;
  image?: CoverImage;
  category?: ProductCategoryReference;
  store?: "amazon" | "shein" | "other";
  affiliateUrl?: string;
  shortDescription?: string;
  active?: boolean;
  publishedAt?: string;
};

export type ProductCategory = {
  _id: string;
  _type: "productCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: {
    es?: string;
    en?: string;
  };
  slug?: {
    es?: string;
    en?: string;
  };
};

export type BlogCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogCategory";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: BlockContent;
  coverImage?: CoverImage;
  category?: BlogCategoryReference;
  tags?: Array<string>;
  publishedAt?: string;
  featured?: boolean;
  seo?: Seo;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: {
    es?: string;
    en?: string;
  };
  slug?: {
    es?: string;
    en?: string;
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Brand
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SiteSettings
  | ProductReference
  | ProductList
  | YoutubeEmbed
  | Seo
  | CoverImage
  | BlockContent
  | TranslationMetadata
  | InternationalizedArrayReference
  | PostReference
  | InternationalizedArrayReferenceValue
  | ProductCategoryReference
  | Product
  | ProductCategory
  | BlogCategoryReference
  | AuthorReference
  | Post
  | BlogCategory
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
